apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
type: Opaque
stringData:
  database-name: {{ .Values.databaseName }}
  database-password: {{ .Values.databasePassword }}
  database-root-password: {{ .Values.databaseRootPassword }}
  database-user: {{ .Values.databaseUser }}
